services:
  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      api-1:
        condition: service_started
      api-2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"
    networks:
      - rinha

  api-1:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      - INDEX_DIR=/data/index
      - LIB_PATH=/app/src/libvector.so
      - NPROBE=10
      - WORKERS=2
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "170MB"
    networks:
      - rinha

  api-2:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      - INDEX_DIR=/data/index
      - LIB_PATH=/app/src/libvector.so
      - NPROBE=10
      - WORKERS=2
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "170MB"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
