services:
  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      api-1:
        condition: service_started
      api-2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "25MB"
    networks:
      - rinha

  api-1:
    image: sschonss/rinha-api-2026:v8
    platform: linux/amd64
    environment:
      - INDEX_DIR=/data/index
      - LIB_PATH=/app/src/libvector.so
      - NPROBE=5
      - WORKERS=1
      - PORT=9999
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "162MB"
    networks:
      - rinha

  api-2:
    image: sschonss/rinha-api-2026:v8
    platform: linux/amd64
    environment:
      - INDEX_DIR=/data/index
      - LIB_PATH=/app/src/libvector.so
      - NPROBE=5
      - WORKERS=1
      - PORT=9999
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "162MB"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
